---
- hosts: localhost
  vars:
    lvars: |
           line 1
           line 2 
           line 3
           line 4
           line 5
           line 6
  tasks:
    - name: Multiline variable
      debug: msg="This is {{ item }}"
      with_items: "{{ lvars.split('\n') }}"
