---
- hosts: localhost
  vars:
    imvar: "{{ imanothervar }}"
    imanothervar: "{{ imanothervar1 }}"
    imanothervar1: "{{ imanothervar2 }}"
    imanothervar2: You are dreaming
  tasks:
    - name: Inception with variable 
      debug: msg="{{ imvar  }}"
